
name: Ejecución diaria de apertura

on:
  schedule:
    # Apertura: De lunes a viernes a las 14:00 UTC
    - cron: "0 14 * * 1-5"
  workflow_dispatch: # Permite ejecución manual
jobs:
  apertura:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cargar secretos en .env
        run: |
          echo "TICKERS=${{ secrets.TICKERS }}" >> config.env
          echo "bearer_token=${{ secrets.BEARER_TOKEN }}" >> config.env
          echo "api_key=${{ secrets.API_KEY }}" >> config.env
          echo "api_secret=${{ secrets.API_SECRET }}" >> config.env
          echo "access_token=${{ secrets.ACCESS_TOKEN }}" >> config.env
          echo "access_token_secret=${{ secrets.ACCESS_TOKEN_SECRET }}" >> config.env
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> config.env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> config.env
          echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" >> config.env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> config.env
          echo "EMAIL_RECEIVER=${{ secrets.EMAIL_RECEIVER }}" >> config.env

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar apertura
        run: python apertura.py

